#!/usr/bin/env bash
#==========================================================================
# Initial author(2021_02_16): Martin.Vahi@softf1.com
# This file is in public domain.
#
# The following line is a spdx.org license label line:
# SPDX-License-Identifier: 0BSD
#==========================================================================
S_TIMESTAMP="`date +%Y`_`date +%m`_`date +%d`_T_`date +%H`h_`date +%M`min_`date +%S`s"
S_FP_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" # the parent folder of this script file
#--------------------------------------------------------------------------
S_FP_TMP="$S_FP_DIR/bonnet/tmp_"
mkdir -p "$S_FP_TMP" ; sync; wait # for USB drives, network drives, etc.
if [ ! -e "$S_FP_TMP" ]; then
    echo ""
    echo "Failed to create "
    echo ""
    echo "    $S_FP_TMP"
    echo ""
    echo "GUID=='4dfd8613-fbb9-482f-8737-2330e00125e7'"
    echo ""
    exit 1
fi
S_TMP_0="_autogenerated_testscript.bash"
S_FP_TMP_BASH="$S_FP_TMP/$S_TIMESTAMP$S_TMP_0"
cat "$S_FP_DIR/bonnet/core.bash"  > $S_FP_TMP_BASH ; sync; wait 
if [ ! -e "$S_FP_TMP_BASH" ]; then
    echo ""
    echo "Failed to create "
    echo ""
    echo "    $S_FP_TMP_BASH"
    echo ""
    echo "GUID=='214f606a-af92-41b5-b727-2330e00125e7'"
    echo ""
    exit 1
fi
#--------------------------------------------------------------------------
# The 
# cat ./one_program_per_line.txt | sed -e 's/[\#].*//g' | sed -e 's/ //g' | sed -e "s/$(printf '\t')//g" | sed -e '/^$/d' 
# outputs commentless text and 
cat "$S_FP_DIR/one_program_per_line.txt" | sed -e 's/[\#].*//g' | sed -e 's/ //g' | sed -e "s/$(printf '\t')//g" | sed -e '/^$/d' \
  | sed -e 's/^/t "/' | sed -e 's/$/"/' >> $S_FP_TMP_BASH 
sync; wait 
nice -n 15 bash "$S_FP_TMP_BASH" "$S_TIMESTAMP"
rm -f "$S_FP_TMP_BASH"

